name: CI

on:
  push:
    branches: [ main, release* ]
    tags: [ v* ]
  pull_request:
    branches: [ main, release* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BUILD_ARTIFACTS_FOLDER: build_artifacts

    steps:
      - name: "[Setup] - Checkout code"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "[Setup] - Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "[Setup] - Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
          bundler-cache: true

      - name: "[Setup] - Install CycloneDX CLI"
        run: |
          cd bin
          curl -LO https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.0/cyclonedx-linux-x64
          chmod a+x cyclonedx-linux-x64
          mv cyclonedx-linux-x64 cyclonedx
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        

      - name: "[Lint] - run linters"
        run: |
          ./bin/lint.rb

      - name: "[Build] - run build"
        run: |
          ./bin/build.rb
          
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true

      - name: "[Test] - run all tests"
        run: |
          ./bin/test.rb --skip-build
