name: CI

on:
  push:
    branches: [ main, release* ]
    tags: [ v* ]
  pull_request:
    branches: [ main, release* ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [ '8', '11', '17' ]

    runs-on: ${{ matrix.os }}
    env:
      BUILD_ARTIFACTS_FOLDER: build_artifacts

    steps:
      - name: "[Setup] - Checkout code"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "[Setup] - Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: "[Setup] - Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true

      - name: "[Setup] - Install CycloneDX CLI (Windows)"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd bin
          Invoke-WebRequest -Uri https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.0/cyclonedx-win-x64.exe -OutFile cyclonedx.exe
          echo "$env:GITHUB_WORKSPACE\bin"
          "$env:GITHUB_WORKSPACE\bin" >> $env:GITHUB_PATH
          cd ..
          cyclonedx --help

      - name: "[Setup] - Install CycloneDX CLI (Linux)"
        if: runner.os != 'Windows'
        run: |
          cd bin
          curl -LO https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.0/cyclonedx-linux-x64
          chmod a+x cyclonedx-linux-x64
          mv cyclonedx-linux-x64 cyclonedx
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH


      - name: "[Lint] - run linters"
        run: |
          ruby ./bin/lint.rb

      - name: "[Build] - run build"
        run: |
          ruby ./bin/build.rb

      - name: "[Test] - run all tests"
        run: |
          ruby ./bin/test.rb --skip-build
